version: '3.1'
services:
  stats-server:
    build: ewm-stat/ewm-stat-server
    image: benito/stats-server:v0.1
    container_name: stats-server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
       SPRING_DATASOURCE_URL: "jdbc:postgresql://stats-db:5432/ewm-stats"
       POSTGRES_USER: "ewm"
       POSTGRES_PASSWORD: "iamroot"

  stats-db:
    image: postgres:14-alpine3.18
    container_name: stats-db-container
    ports:
      - "6541:5432"
    environment:
       POSTGRES_DB: "ewm-stats"
       POSTGRES_USER: "ewm"
       POSTGRES_PASSWORD: "iamroot"

  ewm-service:
    build: ewm-main/
    image: benito/ewm-main-service:v0.1
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://ewm-db:5433/ewm-main"
      POSTGRES_USER: "ewm"
      POSTGRES_PASSWORD: "iamroot"

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-main-db-container
    ports:
      - "6542:5433"
    environment:
      POSTGRES_DB: "ewm-main"
      POSTGRES_USER: "ewm"
      POSTGRES_PASSWORD: "iamroot"