DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS location CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS participation_requests CASCADE;
DROP TABLE IF EXISTS events_status CASCADE;
DROP TABLE IF EXISTS participation_requests_status CASCADE;

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(64) NOT NULL,
    user_email VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_annotation VARCHAR(2000) NOT NULL,
    event_category_id BIGINT,  -- FK categories(category_id)
    event_confirmed_requests BIGINT,
    event_created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_initiator_id BIGINT NOT NULL, -- FK users(user_id)
    event_location_id BIGINT NOT NULL, -- FK locations(location_id)
    is_event_paid BOOLEAN NOT NULL,
    event_participant_limit BIGINT NOT NULL,
    event_published_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    is_event_participant_request_moderation BOOLEAN NOT NULL,
    event_status_id INT NOT NULL, -- FK events_status(status_id)
    event_title VARCHAR(128) NOT NULL,
    event_views BIGINT
);

CREATE TABLE IF NOT EXISTS locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_lat FLOAT NOT NULL,
    location_lot FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS categories(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_title VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events_status (
    status_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status_name VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilations (
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_title VARCHAR(128) NOT NULL,
    compilation_events_id BIGINT,
    is_pinned_compilation BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS participation_requests (
    participation_request_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    participation_request_event_id BIGINT NOT NULL,
    participation_request_requester_id BIGINT NOT NULL,
    participation_request_created_on TIMESTAMP WITHOUT TIME ZONE,
    participation_request_status_id INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS participation_requests_status (
  status_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  status_name VARCHAR(64) NOT NULL UNIQUE
);