DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS categories CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS locations CASCADE;
DROP TABLE IF EXISTS compilations CASCADE;
DROP TABLE IF EXISTS requests CASCADE;
DROP TABLE IF EXISTS events_status CASCADE;
DROP TABLE IF EXISTS requests_status CASCADE;
DROP TABLE IF EXISTS events_compilations CASCADE;

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(250) NOT NULL,
    user_email VARCHAR(254) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    category_id BIGINT,  -- FK categories(category_id)
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id BIGINT NOT NULL, -- FK users(user_id)
    location_id BIGINT NOT NULL, -- FK locations(location_id)
    is_event_paid BOOLEAN NOT NULL,
    event_participant_limit BIGINT NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    is_event_participant_request_moderation BOOLEAN NOT NULL,
    event_state VARCHAR(64) NOT NULL,
    title VARCHAR(128) NOT NULL,
    views BIGINT,
    confirmed_requests INTEGER
);

CREATE TABLE IF NOT EXISTS locations (
    location_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_lat FLOAT NOT NULL,
    location_lon FLOAT NOT NULL
);

CREATE TABLE IF NOT EXISTS categories(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_name VARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS compilations (
    compilation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    compilation_title VARCHAR(128) NOT NULL,
    compilation_events_id BIGINT, -- FK events(event_id)
    is_pinned_compilation BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL, -- FK events(event_id)
    requester_id BIGINT NOT NULL, -- FK users(user_id)
    created_on TIMESTAMP WITHOUT TIME ZONE,
    state VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS events_compilations (
    event_id BIGINT,
    compilation_id BIGINT
);

CREATE TABLE IF NOT EXISTS events_requests (
    event_id BIGINT,
    request_id BIGINT
);

ALTER TABLE events ADD FOREIGN KEY (location_id) REFERENCES locations(location_id);
ALTER TABLE events ADD FOREIGN KEY (initiator_id) REFERENCES users(user_id);
ALTER TABLE events ADD FOREIGN KEY (category_id) REFERENCES categories(id);

ALTER TABLE requests ADD FOREIGN KEY (event_id) REFERENCES events(id);
ALTER TABLE requests ADD FOREIGN KEY (requester_id) REFERENCES users(user_id);

ALTER TABLE events_compilations ADD FOREIGN KEY (event_id) REFERENCES events(id);
ALTER TABLE events_compilations ADD FOREIGN KEY (compilation_id) REFERENCES compilations(compilation_id);

ALTER TABLE events_requests ADD FOREIGN KEY (event_id) REFERENCES events(id);
ALTER TABLE events_requests ADD FOREIGN KEY (request_id) REFERENCES requests(id);

